name: CI
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        include:
          - os: 'macos-13'
            python-version: '3.6'
          - os: 'windows-latest'
            python-version: '3.6'
          - os: 'ubuntu-22.04'
            python-version: '3.7'
          - os: 'macos-13'
            python-version: '3.7'
          - os: 'windows-latest'
            python-version: '3.7'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install coverage pytest
          pip install -e .
      - name: Lint
        continue-on-error: true
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github
          src: .
      - name: Test
        run: |
          coverage run -m pytest
      - name: Report Coverage
        run: |
          coverage report -m